version: '2'
services:

    §§INSTANCE-paintomics3:
      image: fikipollo/paintomics3
      container_name: §§INSTANCE-paintomics3
      environment:
        - ADMIN_EMAIL=§§ADMIN_EMAIL
        - ADMIN_PASS=§§ADMIN_PASS
        - ADMIN_AFFILIATION=§§ADMIN_AFFILIATION
      links:
        - §§INSTANCE-paintomics3-mongo:paintomics3-mongo
      depends_on:
        - §§INSTANCE-paintomics3-mongo
      volumes_from:
        - §§INSTANCE-paintomics3-data
      ports:
        - "§§PORT:80"

    §§INSTANCE-paintomics3-mongo:
      image: mongo
      container_name: §§INSTANCE-paintomics3-mongo
      depends_on:
        - §§INSTANCE-paintomics3-data
      volumes_from:
        - §§INSTANCE-paintomics3-data

    §§INSTANCE-paintomics3-data:
      image: busybox
      container_name: §§INSTANCE-paintomics3-data
      volumes:
        - §§FOLDER/data/paintomics3:/data/paintomics3
        - §§FOLDER/data/db:/data/db
        - §§FOLDER/conf:/usr/local/apache2/htdocs/PaintomicsServer/src/conf/
